site_name: CanaryBananas
theme:
  name: material
  language: es     # o 'ca' si quieres catalán
  logo: img/logo.png       # Logo que aparece en la cabecera
  favicon: img/images.png # Icono que aparece en la pestaña del navegador

nav:
  - Historia: historia.md
  - Resultados: cuentas.md
  - Personal: personal.md
  - IT: it.md
  - Consultor: consultor.md
  - Base Excel: excel.md

extra_css:
  - css/base.css

plugins:
 - mermaid2:
      version: 10.0.2
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
 - search:
      lang: es     # opcional: mejora el buscador para español



